# Generated by Django 6.0.6 on 2026-06-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_deal_next_check_pending_at'),
        ('linkedin', '0010_leadlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='linkedin.leadlist'),
        ),
    ]
