# Generated by Django 6.0.6 on 2026-06-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_lead_lead_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
