# Generated by Django 6.0.6 on 2026-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_company_lead_first_name_lead_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
