# Generated by Django 6.0.6 on 2026-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_lead_location_lead_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_score',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
