# Generated by Django 6.0.6 on 2026-06-07 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_lead_lead_list'),
        ('linkedin', '0010_leadlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lead_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='linkedin.leadlist'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('message', 'Message'), ('inmail', 'InMail'), ('profile_visit', 'Profile Visit'), ('like_post', 'Like Post')], max_length=20),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='linkedin.sequence'),
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('root', 'Root'), ('success', 'Success'), ('failure', 'Failure')], default='root', max_length=10)),
                ('step_type', models.CharField(choices=[('connect', 'Send Connection Request'), ('message', 'Send Message'), ('inmail', 'Send InMail'), ('wait', 'Wait'), ('profile_visit', 'View Profile'), ('like_post', 'Like Post')], max_length=20)),
                ('order_in_branch', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='linkedin.sequencestep')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='linkedin.sequence')),
            ],
            options={
                'ordering': ['order_in_branch'],
            },
        ),
        migrations.AddField(
            model_name='actionlog',
            name='sequence_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='linkedin.sequencestep'),
        ),
        migrations.CreateModel(
            name='LeadCampaignState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_branch', models.CharField(choices=[('root', 'Root'), ('success', 'Success'), ('failure', 'Failure')], default='root', max_length=10)),
                ('state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped_reply', 'Stopped — replied'), ('stopped_error', 'Stopped — error'), ('paused_manual', 'Paused (manual)'), ('archived', 'Archived')], default='active', max_length=20)),
                ('awaiting_decision', models.BooleanField(default=False)),
                ('next_action_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_states', to='linkedin.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_states', to='crm.lead')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='linkedin.sequencestep')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_action_due_at'], name='linkedin_le_state_c38165_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'campaign'), name='unique_lead_campaign_state')],
            },
        ),
    ]
