# Generated by Django 6.0.6 on 2026-06-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0012_messagethread_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='has_inmail',
            field=models.BooleanField(default=False),
        ),
    ]
