# Generated by Django 6.0.6 on 2026-06-07 23:22

import django.db.models.deletion
import linkedin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0013_linkedinprofile_has_inmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='daily_caps_json',
            field=models.JSONField(blank=True, default=linkedin.models.default_daily_caps),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccountDailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action_type', models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('message', 'Message'), ('inmail', 'InMail'), ('profile_visit', 'Profile Visit'), ('like_post', 'Like Post')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counters', to='linkedin.linkedinprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'date'], name='linkedin_ac_account_24f7b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'date', 'action_type'), name='unique_counter_per_account_day_action')],
            },
        ),
    ]
