# Generated by Django 6.0.6 on 2026-06-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0014_linkedinprofile_daily_caps_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
