# Generated by Django 6.0.6 on 2026-06-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0015_linkedinprofile_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinprofile',
            name='connect_daily_limit',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
