# Generated by Django 6.0.6 on 2026-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0016_alter_linkedinprofile_connect_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadlist',
            name='pending_search',
            field=models.BooleanField(default=False),
        ),
    ]
