# Generated by Django 6.0.6 on 2026-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0017_leadlist_pending_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pending_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leadlist',
            name='source_type',
            field=models.CharField(choices=[('csv', 'CSV upload'), ('search_url', 'LinkedIn search URL'), ('ai', 'AI lead finder'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
