# Generated by Django 6.0.6 on 2026-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0018_message_pending_send_alter_leadlist_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='ai_context',
            field=models.TextField(blank=True, default=''),
        ),
    ]
