# Generated by Django 6.0.6 on 2026-06-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0019_siteconfig_ai_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='inmail_monthly_cap',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
