# Generated by Django 6.0.6 on 2026-06-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0020_linkedinprofile_inmail_monthly_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadlist',
            name='target_count',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
