# Generated by Django 6.0.6 on 2026-06-08 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0021_leadlist_target_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadListEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'You'), ('ai', 'AI'), ('system', 'System')], max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='linkedin.leadlist')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
