# Generated by Django 6.0.6 on 2026-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0022_leadlistevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencestep',
            name='step_type',
            field=models.CharField(choices=[('connect', 'Send Connection Request'), ('message', 'Send Message'), ('inmail', 'Send InMail'), ('wait', 'Wait'), ('profile_visit', 'View Profile'), ('like_post', 'Like Post'), ('end', 'End — stop here')], max_length=20),
        ),
    ]
