# Generated by Django 6.0.6 on 2026-06-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0023_alter_sequencestep_step_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='contacted_by_tool',
            field=models.BooleanField(default=False),
        ),
    ]
