# Generated by Django 6.0.6 on 2026-06-08 21:19

import linkedin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0024_messagethread_contacted_by_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='holiday_country',
            field=models.CharField(default='GB', max_length=8),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='send_end_hour',
            field=models.PositiveSmallIntegerField(default=17),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='send_start_hour',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='send_timezone',
            field=models.CharField(default='Europe/London', max_length=64),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='send_weekdays',
            field=models.JSONField(blank=True, default=linkedin.models.default_send_weekdays),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='skip_bank_holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sequencestep',
            name='step_type',
            field=models.CharField(choices=[('connect', 'Send Connection Request'), ('message', 'Send Message'), ('inmail', 'Send InMail'), ('wait', 'Wait'), ('profile_visit', 'View Profile'), ('like_post', 'Like Post'), ('end', 'End — stop here'), ('blank', 'Blank — no action (resume)')], max_length=20),
        ),
    ]
