# Generated by Django 6.0.6 on 2026-06-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0025_linkedinprofile_holiday_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='connect_random_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='connect_random_max',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='connect_random_min',
            field=models.PositiveSmallIntegerField(default=19),
        ),
    ]
