# Generated by Django 6.0.6 on 2026-06-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0026_linkedinprofile_connect_random_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='slack_notify_replies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='slack_webhook_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
