# Generated by Django 6.0.6 on 2026-06-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_lead_ai_reason_lead_ai_score'),
        ('linkedin', '0027_siteconfig_slack_notify_replies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='accountdailycounter',
            name='action_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('message', 'Message'), ('inmail', 'InMail'), ('profile_visit', 'Profile Visit'), ('like_post', 'Like Post'), ('connect_accepted', 'Connection accepted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('message', 'Message'), ('inmail', 'InMail'), ('profile_visit', 'Profile Visit'), ('like_post', 'Like Post'), ('connect_accepted', 'Connection accepted')], max_length=20),
        ),
    ]
