# Generated by Django 6.0.6 on 2026-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0028_actionlog_lead_alter_accountdailycounter_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='target_url',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
